[package]
name = "bandersnatch_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sha2 = "0.10"
ark-ec-vrfs = { git = "https://github.com/davxy/ark-ec-vrfs.git", branch = "main", features = ["ring", "bandersnatch"] }
