[package]
name = "bandersnatch_ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ark-vrf = { version = "0.1.0", features = ["ring", "bandersnatch"] }
once_cell = "1.18.0"

[dev-dependencies]
hex = "0.4"
